/*M!999999\- enable the sandbox mode */ 

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

LOCK TABLES `researches` WRITE;
/*!40000 ALTER TABLE `researches` DISABLE KEYS */;
INSERT INTO `researches` VALUES
('armor_tech','Forge & Métallurgie du Tamahagane',2000,800,0,240,'Améliore la résistance des armures laquées et des lames forgées.'),
('energy_tech','Méditation Shintō & Sérénité',800,400,200,150,'Renforce l\'harmonie spirituelle et la ferveur dans l\'ensemble du domaine.'),
('espionage_tech','Réseau de Renseignements Shinobi',500,1000,300,180,'Permet aux informateurs d\'obtenir des rapports détaillés sur les fiefs rivaux.'),
('laser_tech','Art du Tir & Poudre Noire',1200,600,100,210,'Perfectionne la puissance de feu des archers et des arquebusiers.'),
('propulsion_tech','Art Militaire des Relais de Poste',1500,1500,600,300,'Améliore la rapidité de déplacement des coursiers et des armées provinciales.'),
('shield_tech','Tactique de Mur de Pavois',1000,1200,500,270,'Renforce la résistance des palissades et boucliers face aux tirs ennemis.'),
('warp_tech','Grandes Voies Stratégiques (Gokaidō)',5000,10000,4000,600,'Trace les grandes routes impériales permettant les marches accélérées d\'armées de siège.');
/*!40000 ALTER TABLE `researches` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `ships` WRITE;
/*!40000 ALTER TABLE `ships` DISABLE KEYS */;
INSERT INTO `ships` VALUES
('aethelis_mirage','Embuscade Shinobi Montée','aethelis','shinobi_monte_tokugawa.jpg',3500,1500,200,65,350,50,14000,60,360,'Troupe furtive Tokugawa expertisant le terrain et prenant l\'ennemi à revers.'),
('aethelis_prism','Catapulte Flamboyante Horokubiya','aethelis','catapulte_horokubiya_tokugawa.jpg',22000,9000,3000,450,2200,250,9000,900,2100,'Projette des bombes incendiaires et pots de poudre sur les positions ennemies.'),
('aethelis_titan','Forteresse Roulante Blindée','aethelis','forteresse_roulante_tokugawa.jpg',50000,30000,15000,1300,7500,900,6500,2500,4800,'Bastion mobile fortifié protégeant les troupes lors des marches provinciales.'),
('colony_ship','Expédition d\'Établissement Castral','all','expedition_etablissement_castral.jpg',20000,30000,10000,50,3000,200,2500,10000,10800,'Troupe de pionniers et maîtres charpentiers pour ériger un nouveau fief sur des terres fertiles.'),
('spy_probe','Éclaireur Shinobi Furtif','all','eclaireur_shinobi_furtif.jpg',0,1000,200,1,10,1,20000,5,90,'Messager discret et éclaireur rapide capable d\'espionner un fief lointain en silence.'),
('terran_cruiser','Bélier Blindé à Éperon d\'Acier','terran','belier_acier_oda.jpg',20000,7000,2000,400,2500,150,8000,800,1500,'Engin de siège lourd renforcé pour fracasser les portes fortifiées des châteaux.'),
('terran_dreadnought','Grande Tour de Siège & Baliste','terran','tour_siege_baliste_oda.jpg',45000,25000,10000,1200,8000,600,5000,2000,4200,'Machine de guerre monumentale pilonnant les forteresses et murailles ennemies.'),
('terran_interceptor','Cavalier Léger d\'Interception','terran','cavalier_interception_oda.jpg',3000,1000,0,60,400,20,12000,50,300,'Cavalier rapide patrouillant aux frontières provinciales du clan Oda.'),
('transporter_heavy','Grand Convoi Logistique de Fief','all','grand_convoi_logistique.jpg',6000,6000,2000,10,800,50,4000,25000,600,'Longue caravane de transporteurs convoyant d\'immenses cargaisons de riz et de pierre.'),
('transporter_light','Chariot de Ravitaillement Léger','all','chariot_ravitaillement_leger.jpg',2000,2000,500,5,200,10,5000,5000,240,'Convoi de bêtes de somme pour acheminer le riz et les matériaux de construction.'),
('vorash_drone','Cavalier Éclaireur Takeda','vorash','cavalier_eclaireur_takeda.jpg',2200,800,0,55,300,10,13000,80,270,'Cavalier rapide d\'assaut menant les raids fulgurants.'),
('vorash_leviathan','Bélier Titanesque du Dragon de Kai','vorash','belier_dragon_kai.jpg',40000,20000,8000,1100,7000,450,6000,3000,3000,'Engin de guerre colossal écrasant toute résistance sous sa masse.'),
('vorash_manticore','Escadron de Cavalerie Cuirassée','vorash','cavalerie_cuirassee_takeda.jpg',16000,6000,1500,380,2000,100,9500,1200,900,'Fer de lance des raids de pillage impitoyables du clan Takeda.');
/*!40000 ALTER TABLE `ships` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `units` WRITE;
/*!40000 ALTER TABLE `units` DISABLE KEYS */;
INSERT INTO `units` VALUES
('archer_protecteur_muraille','Archer Protecteur de Muraille','aethelis',2,'🏹','archer_protecteur_muraille.jpg',90,180,60,22,70,65,7,30,220,'Archer d\'élite tirant des volées de flèches protectrices depuis les créneaux du château.'),
('archer_yumi_monte','Archer Yumi Monté','vorash',2,'🏹','archer_yumi_monte.jpg',80,130,30,20,55,60,6,25,200,'Cavalier archer agile harcelant les convois et défenses à distance.'),
('arquebusier_oda_tanegashima','Arquebusier Oda (Tanegashima)','terran',2,'🎯','arquebusier_oda_tanegashima.jpg',100,150,40,25,65,55,6,35,210,'Tireur d\'élite armé du mousquet à mèche japonais Tanegashima avec une formidable puissance perforante.'),
('cavalier_rouge_akazonae','Cavalier Rouge de Choc (Akazonae)','vorash',3,'🐎','cavalier_rouge_akazonae.jpg',220,160,60,95,35,25,8,80,540,'Légendaire cavalerie rouge d\'assaut du clan Takeda, perçant toute muraille sous la charge.'),
('fantassin_leger_takeda','Fantassin Léger Takeda','vorash',1,'🗡️','fantassin_leger_takeda.jpg',90,70,15,45,20,15,9,65,80,'Guerrier conscrit vif et féroce lancé à vive allure à l\'assaut des réserves adverses.'),
('garde_hatamoto_armure_lourde','Garde Hatamoto en Armure Lourde','terran',4,'🥋','garde_hatamoto_armure_lourde.jpg',600,450,250,210,120,150,5,120,1200,'Champion en armure laquée ornée de la garde rapprochée du Daimyō, brisant les lignes de défense.'),
('hatamoto_venerable_tokugawa','Hatamoto Vénérable Tokugawa','aethelis',4,'🏯','hatamoto_venerable_tokugawa.jpg',650,500,300,200,140,160,6,110,1300,'Garde imprenable au grand pavois d\'acier, roc inébranlable du domaine.'),
('loup_honshu','Loup Vicieux de Honshu','all',2,'🐺','loup_honshu.jpg',0,0,0,60,35,55,9,0,0,'Prédateur rusé chassant en meute coordonnée dans les forêts et collines.'),
('maitre_nodachi_kai','Guerrier Maître Nodachi de Kai','vorash',4,'⚡','maitre_nodachi_kai.jpg',550,400,200,225,110,130,5,140,1150,'Colosse maniant la redoutable et gigantesque lame nodachi pour fendre armures et chevaux.'),
('ombre_shinobi_infiltree','Ombre Shinobi Infiltrée','aethelis',3,'🥷','ombre_shinobi_infiltree.jpg',240,210,90,90,40,35,9,60,450,'Maître espion et assassin furtif se glissant sans bruit derrière les lignes ennemies.'),
('ours_hokkaido','Grand Ours Brun de Hokkaido','all',3,'🐻','ours_hokkaido.jpg',0,0,0,140,130,110,6,0,0,'Colosse sauvage des contrées septentrionales, doué d\'une force brute titanesque.'),
('piquier_ashigaru_yari','Piquier Ashigaru (Yari)','terran',1,'🎋','piquier_ashigaru_yari.jpg',120,100,30,40,35,20,7,50,90,'Fantassin de base discipliné de l\'armée Oda, maniant la longue lance yari avec rigueur.'),
('samourai_katana','Samouraï au Katana','terran',3,'⚔️','samourai_katana.jpg',250,180,80,85,45,30,8,70,480,'Noble bretteur d\'élite au moral d\'acier, expert dans le combat rapproché au fil tranchant.'),
('sanglier_sauvage','Sanglier Enragé des Monts','all',1,'🐗','sanglier_sauvage.jpg',0,0,0,35,40,20,7,0,0,'Bête sauvage agressive chargeant en furie quiconque s\'approche de sa tanière.'),
('sentinelle_yari_tokugawa','Sentinelle Yari Tokugawa','aethelis',1,'🛡️','sentinelle_yari_tokugawa.jpg',110,120,40,42,38,25,8,45,95,'Garde défensif dévoué à la protection imprenable du domaine castral.'),
('colonizer','Pionnier Féodal (Colon)','all',3,'⛩️','expedition_etablissement_castral.jpg',4500,4000,4500,10,30,20,4,3000,7200,'Troupe de pionniers et maîtres charpentiers équipés pour fonder un nouveau village castral indépendant.');
/*!40000 ALTER TABLE `units` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `game_settings` WRITE;
/*!40000 ALTER TABLE `game_settings` DISABLE KEYS */;
INSERT INTO `game_settings` VALUES
('beginner_protection_days','7','int','Durée de l\'immunité féodale des nouveaux joueurs en jours (0 pour désactiver)','2026-09-23 12:00:00'),
('bot_aggressiveness','aggressive','string','Comportement des bots (peaceful, moderate, aggressive)','2026-09-19 08:08:06'),
('bot_colonize_enabled','1','boolean','Autoriser les bots à coloniser de nouvelles planètes','2026-09-19 08:08:06'),
('bot_last_tick_time','1789823017','string',NULL,'2026-09-19 15:03:37'),
('bot_max_planets','3','int','Nombre maximum de planètes par bot','2026-09-19 08:08:06'),
('bots_enabled','1','boolean','Activation globale de l\'intelligence artificielle des bots','2026-09-19 08:08:06'),
('fleet_speed','1','int','Multiplicateur de vitesse de vol des convois spatiaux','2026-09-19 08:08:06'),
('game_speed','1','int','Multiplicateur de vitesse des constructions, chantiers, caserne et recherches','2026-09-19 08:08:06'),
('oasis_density_percent','1.5','float','Pourcentage de couverture d\'oasis naturelles sur la carte (en %)','2026-09-19 08:08:06'),
('oasis_respawn_on_capture','1','boolean','Fait réapparaître une nouvelle oasis sauvage dès qu\'une oasis est capturée par un joueur','2026-09-19 08:08:06'),
('resource_speed','1','int','Multiplicateur de production horaire des mines et extracteurs','2026-09-19 08:08:06');
/*!40000 ALTER TABLE `game_settings` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `authentic_castles` WRITE;
/*!40000 ALTER TABLE `authentic_castles` DISABLE KEYS */;
INSERT INTO `authentic_castles` VALUES
(1,'bitchu_matsuyama','Château de Bitchū Matsuyama','Bitchū Matsuyama-jō','備中松山城','Province de Bitchū (Takahashi, Préfecture d\'Okayama)','Akiba Shigenobu (1240) / Mizunoya Katsutaka (1683)','1683','Bien Culturel Important & Plus Haut Donjon de Montagne','🏯','bitchu_matsuyama.jpg','Unique donjon de montagne (yamajiro) d\'époque Edo encore préservé au Japon, perché à 430 mètres d\'altitude au-dessus d\'une mer de nuages.','Érigé sur le sommet escarpé du mont Gagyū, le château de Bitchū Matsuyama est un chef-d\'œuvre d\'ingénierie médiévale tirant parti des falaises abruptes pour créer une forteresse réputée imprenable. Au petit matin d\'automne, les brumes matinales submergent la vallée de Takahashi, laissant émerger le donjon blanc au-dessus des nuages, lui conférant le surnom légendaire de « Château dans le Ciel ». Sa structure à deux niveaux en bois de cyprès repose directement sur un affleurement de roche mère naturelle.','• Donjon de montagne (yamajiro) le plus élevé du Japon (430 m).\\n• Murailles de pierre sèches épousant les failles granitiques de la falaise.\\n• Tours d\'angle Ote-mon et tourelle à deux niveaux San-no-maru parfaitement conservées.','Position zénithale dominante. Perché au-dessus des brumes, Bitchū Matsuyama offre une visibilité totale sur tous les mouvements militaires ennemis dans le centre de l\'archipel. En cas d\'assaut massif lors de la Bataille Finale, son relief escarpé divise par deux l\'efficacité des troupes d\'assaut adverses.','Sceau du Sanctuaire Céleste : Confère +15% de résistance défensive à toutes les garnisons du clan.',-18,-18,-18,-18,1,NULL,25000,NULL,NULL,'2026-09-15 09:49:35'),
(2,'hikone','Château de Hikone','Hikone-jō','彦根城','Province d\'Ōmi (Préfecture de Shiga)','Ii Naomasa & Ii Naotsugu (Clan Ii)','1603 - 1622','Trésor National du Japon','🏯','hikone.jpg','Forteresse légendaire des Diables Rouges (Akazonae) du clan Ii, surveillant le lac Biwa et verrouillant l\'accès à Kyōto.','Édifié après la bataille décisive de Sekigahara par le général Ii Naomasa sur les rives stratégiques du lac Biwa, le château de Hikone a été conçu pour prévenir toute rébellion contre le Shogunat Tokugawa. Son donjon à trois étages intègre des éléments recyclés de châteaux antérieurs dont celui d\'Otsu et de Nagahama. Doté d\'une richesse ornementale exceptionnelle combinant toits en pignon courbé (karahafu) et frontons triangulaires (irimoya-hafu), il est resté le fief inexpugnable des seigneurs héréditaires Ii pendant plus de 250 ans.','• Donjon à trois niveaux et trois étages avec toitures étagées variées.\\n• Cloche d\'alarme de garde Tsugibue veillant sur le détroit du lac Biwa.\\n• Écuries seigneuriales d\'origine et pont à bascule défensif Tenbin-yagura.','Verrou de la route de la Capitale. Contrôler Hikone permet de bloquer l\'avancée des armées hostiles vers Kyōto et la plaine du Kansai. Lors de la Grande Bataille Finale, sa possession octroie une mobilité accrue sur les voies de ravitaillement centrales.','Étendard des Diables Rouges : Confère +10% de puissance d\'assaut et +15% de vitesse de marche à toute la cavalerie.',18,-18,18,-18,1,NULL,25000,NULL,NULL,'2026-09-15 09:49:35'),
(3,'himeji','Château de Himeji','Himeji-jō','姫路城','Province de Harima (Himeji, Préfecture de Hyōgo)','Akamatsu Sadanori / Toyotomi Hideyoshi / Ikeda Terumasa','1601 - 1609','Trésor National du Japon & Patrimoine Mondial UNESCO','🏯','himeji.jpg','Le « Héron Blanc » (Shirasagi-jō), plus grand, plus majestueux et plus sophistiqué complexe fortifié féodal d\'origine de tout le Japon.','Joyau absolu de l\'architecture militaire japonaise, le château de Himeji fascine par son éclatante blancheur de chaux ignifugée rappelant les ailes déployées d\'un héron blanc. Bâti par Ikeda Terumasa au faîte de la puissance féodale, le complexe se compose d\'un donjon principal à 5 niveaux et 7 étages relié par des coursives fortifiées à 3 donjons secondaires (Tenshu complexe de type renritsu-shiki). Son enceinte concentrique compte plus de 80 portes massives, des cours aveugles et des chemins déroutants conçus pour piéger impitoyablement tout assaillant dans des zones de tir croisé meurtrières.','• Donjon principal majestueux à 6 étages et sous-sol culminant à 46 mètres.\\n• Système complexe de 84 portes fortifiées et meurtrières triangulaires, carrées et rondes (sama).\\n• Enduit de plâtre blanc résistant au feu recouvrant l\'intégralité des façades et des tuiles.','Le Siège Suprême du Shogunat. Himeji est l\'enjeu ultime : la coalition qui capture et défend le Héron Blanc gagne le titre d\'Hégémonie Impériale et le droit de proclamer l\'avènement de la nouvelle ère shogunale.','Plumes du Héron Blanc : Augmente de +25% les défenses de muraille et octroie un prestige immense (+250 points d\'Honneur/semaine).',-18,18,-18,18,1,NULL,25000,NULL,NULL,'2026-09-15 09:49:35'),
(4,'hirosaki','Château de Hirosaki','Hirosaki-jō','弘前城','Province de Mutsu (Hirosaki, Préfecture d\'Aomori)','Clan Tsugaru (Tamenobu & Nobuhira)','1611 (Reconstruit en 1810)','Bien Culturel Important & Donjon Boréal','🏯','hirosaki.jpg','Donjon authentique le plus septentrional de l\'archipel, gardien farouche des neiges éternelles et des frontières boréales de Mutsu.','Bâti dans le grand Nord sauvage par le clan Tsugaru pour pacifier et unifier la vaste province de Mutsu, le château de Hirosaki s\'élève au cœur d\'une triple enceinte de douves alimentées par les rivières de fonte glaciaire du mont Iwaki. Après la destruction par la foudre de son donjon d\'origine à 5 étages, la tourelle d\'angle à 3 niveaux a été transformée en donjon principal en 1810. La forteresse est renommée mondialement pour ses milliers de cerisiers entourant ses douves gelées en hiver.','• Seul donjon préservé de l\'époque Edo dans toute la région de Tōhoku.\\n• Portes monumentales en cèdre du Nord et douves concentriques triples.\\n• Structure compacte renforcée contre les froids polaires et les congères.','Bastion des Terres du Nord. Il permet de lever les légions montagnardes de Mutsu et de prendre en tenaille depuis l\'arrière toute armée engagée dans le centre de l\'archipel.','Givre de Mutsu : +15% de vitesse de déplacement des troupes et résistance accrue aux conditions hivernales.',12,31,12,31,1,NULL,25000,NULL,NULL,'2026-09-15 09:49:35'),
(5,'inuyama','Château d\'Inuyama','Inuyama-jō','犬山城','Province d\'Owari (Préfecture d\'Aichi)','Oda Nobuyasu (Oncle d\'Oda Nobunaga)','1537','Trésor National du Japon & Plus Ancien Donjon en Bois','🏯','inuyama.jpg','Le plus ancien donjon en bois d\'origine du Japon, sentinelle ancestrale du clan Oda dominant la rivière Kiso.','Fondé en 1537 par Oda Nobuyasu, oncle du grand unificateur Oda Nobunaga, le château d\'Inuyama est vénéré comme le plus vieux donjon encore debout sur le sol japonais. Dressé fièrement sur un éperon rocheux de 40 mètres surplombant les eaux rapides de la rivière Kiso (surnommée le Rhin japonais), il a été le théâtre de batailles mémorables durant l\'ère Sengoku, notamment lors du conflit entre Toyotomi Hideyoshi et Tokugawa Ieyasu. Son dernier étage est ceinturé par un balcon panoramique extérieur en bois sans rambarde fermée, offrant une vue saisissante sur toute la plaine d\'Owari.','• Boiseries et piliers d\'origine en cèdre et cyprès hinoki datant du XVIe siècle.\\n• Galerie panoramique ouverte circulaire (mawarien) au dernier niveau.\\n• Trésor National de structure bōrōgata primitive.','Le Berceau des Conquérants. Contrôler Inuyama, c\'est réveiller la flamme tactique d\'Oda Nobunaga. Il accélère la mobilisation des armes à feu et confère une clairvoyance tactique sur les mouvements ennemis.','Sagesse des Anciens Oda : Réduit de -15% le coût en ressources de toutes les troupes militaires du clan.',18,18,18,18,1,NULL,25000,NULL,NULL,'2026-09-15 09:49:35'),
(6,'kochi','Château de Kōchi','Kōchi-jō','高知城','Province de Tosa (Préfecture de Kōchi, Shikoku)','Yamauchi Kazutoyo','1601 - 1611 (Rebâti 1748)','Bien Culturel Important & Palais Honmaru Intact','🏯','kochi.jpg','Unique forteresse du Japon ayant conservé à la fois son donjon féodal d\'origine et son somptueux palais seigneurial Honmaru Goten.','Érigé sur la colline d\'Otakasa par Yamauchi Kazutoyo après que Tokugawa Ieyasu lui eut octroyé la province insoumise de Tosa, le château de Kōchi est une merveille d\'exhaustivité. C\'est l\'unique site au Japon où l\'on peut encore admirer à la fois le donjon principal et le palais de résidence du seigneur (Honmaru Goten), ainsi que la porte Ote-mon dans leur configuration originale. Ses murs sont hérissés de piques de fer anti-shinobi (shinobi-gaeshi) et de gouttières massives en pierre (mizu-kiri) conçues pour évacuer les déluges de typhons du Pacifique.',
'• Ensemble complet exceptionnel : Donjon, Palais Honmaru Goten et Porte Ote-mon d\'origine.\\n• Piques de fer recourbées anti-infiltration shinobi (shinobi-gaeshi).\\n• Systèmes de gargouilles de pierre monumentales drainant les pluies de mousson.','Le Bastion Insoumis de Tosa. Véritable verrou de l\'île de Shikoku face à l\'océan Pacifique, Kōchi immunise son détenteur contre les attaques de revers maritimes.','Pacte des Guerriers de Tosa : Augmente de +20% la protection des silos et greniers contre tout pillage adverse.',12,-31,12,-31,1,NULL,25000,NULL,NULL,'2026-09-15 09:49:35'),
(7,'marugame','Château de Marugame','Marugame-jō','丸亀城','Province de Sanuki (Préfecture de Kagawa, Shikoku)','Ikoma Chikamasa & Kyōgoku Takakazu','1597 - 1660','Bien Culturel Important & Plus Hautes Murailles de Pierre','🏯','marugame.jpg','Célèbre pour ses vertigineux remparts de pierre de 60 mètres en éventail (ōgi-no-kōbai), les plus imposants du Japon.','Trônant sur la colline de Kameyama face à la mer intérieure de Seto, le château de Marugame est renommé avant tout pour ses remparts colossaux. Disposés en quatre terrasses successives du pied de la colline jusqu\'au sommet, ces murs de pierre taillée atteignent une hauteur cumulée de plus de 60 mètres. Leur courbure gracieuse, appelée ōgi-no-kōbai (courbure en éventail), s\'incline doucement à la base pour devenir presque verticale au sommet, rendant toute tentative d\'escalade totalement vaine.','• Murailles de pierre les plus hautes du Japon (plus de 60 mètres de dénivelé total).\\n• Courbure en éventail défensive ōgi-no-kōbai empêchant l\'escalade.\\n• Donjon en bois compact à trois niveaux veillant sur les détroits maritimes de Seto.','La Citadelle de Pierre Infranchissable. Face aux machines de siège et aux assauts furieux, les remparts de Marugame absorbent les chocs et réduisent drastiquement les pertes de la garnison.',
'Muraille de Sanuki : Ajoute +2,000 points de structure de base à tous les remparts de cité du clan.',31,-12,31,-12,1,NULL,25000,NULL,NULL,'2026-09-15 09:49:35'),
(8,'maruoka','Château de Maruoka','Maruoka-jō','丸岡城','Province d\'Echizen (Préfecture de Fukui)','Shibata Katsutoyo (1576)','1576','Bien Culturel Important & Toit en Tuiles de Pierre','🏯','maruoka.jpg','Le « Château de la Brume » (Kasumi-ga-jō), donjon primitif d\'Echizen doté d\'une toiture unique en lourdes tuiles de pierre volcanique.','Bâti sur ordre du grand chef de guerre Shibata Katsuie par son neveu Katsutoyo en 1576, Maruoka est l\'un des plus anciens donjons d\'aspect archaïque du Japon. Sa caractéristique la plus fascinante réside dans son toit recouvert de quelque 6 000 tuiles plates sculptées dans la pierre bleue locale d\'Asuwa (shakudani-ishi), matériau conçu pour résister au poids écrasant de la neige et aux incendies. La légende raconte que lorsqu\'un ennemi approche de la forteresse, un serpent géant apparaît et répand un épais brouillard impénétrable qui cache le château aux yeux des assaillants.','• Toiture exceptionnelle pesant plus de 60 tonnes constituée de tuiles de pierre d\'Asuwa.\\n• Escaliers intérieurs en bois extrêmement raides (65 degrés) avec cordes de traction.\\n• Donjon bōrōgata primitif à deux niveaux extérieurs et trois étages intérieurs.','Le Voile de Brume Protectrice. Dans la Bataille Finale, Maruoka dissimule l\'état réel des forces armées du clan et neutralise les tentatives d\'espionnage ennemi.','Voile de Brume d\'Echizen : Immunité accrue contre l\'espionnage shinobi adverse.',-12,31,-12,31,1,NULL,25000,NULL,NULL,'2026-09-15 09:49:35'),
(9,'matsue','Château de Matsue','Matsue-jō','松江城','Province d\'Izumo (Préfecture de Shimane)','Horio Yoshiharu (1607 - 1611)','1611','Trésor National du Japon','🏯','matsue.jpg','Le « Château du Pluvier » (Chidori-jō), imposante citadelle noire aux façades de bois laqué sombre veillant sur la terre des dieux.','Fier Trésor National élevé par le général vétéran Horio Yoshiharu, le château de Matsue domine majestueusement le lac Shinji et la lagune de Nakaumi. Surnommé le « Château du Pluvier » en raison de la ressemblance de ses toits en pignon triangulaire avec les ailes déployées de cet oiseau aquatique, il se distingue par son extérieur austère revêtu de planches de bois noircies à la suie et au tanin protecteur. Bâti dans la province sacrée d\'Izumo où se réunissent les huit millions de divinités shinto, il conserve un impressionnant puits intérieur souterrain de 24 mètres et des trappes à pierres meurtrières (ishi-otoshi).','• Trésor National à 5 niveaux extérieurs et 6 étages intérieurs avec tour de guet supérieure.\\n• Bardage extérieur sombre en bois laqué traité au charbon de bois.\\n• Vastes douves navigables préservées reliées au système fluvial de la cité lacustre.','La Bénédiction des Kami. Siège spirituel de la province d\'Izumo, le contrôle de Matsue rallie la ferveur des fidèles et décuple la sérénité des sanctuaires de toute la faction.','Bénédiction des Kami d\'Izumo : +20% de production de ferveur et sérénité (énergie sacrée) sur tous les domaines.',-31,12,-31,12,1,NULL,25000,NULL,NULL,'2026-09-15 09:49:35'),
(10,'matsumoto','Château de Matsumoto','Matsumoto-jō','松本城','Province de Shinano (Préfecture de Nagano)','Ishikawa Kazumasa & Yasunaga (1592 - 1604)','1604','Trésor National du Japon','🏯','matsumoto.jpg','Le « Château du Corbeau » (Karasu-jō), chef-d\'œuvre d\'ébène laqué à cinq niveaux trônant majestueusement face aux Alpes japonaises.','L\'un des plus beaux et des plus célèbres châteaux du monde, Matsumoto se dresse fièrement sur une plaine entourée de vastes douves étincelantes dans lesquelles se reflètent les sommets enneigés des Alpes du Nord. Son allure noire saisissante, due aux boiseries laquées de suie sombre qui recouvrent ses murs, lui a valu le surnom de « Château du Corbeau » (Karasu-jō). Il dispose d\'une structure complexe unique : un donjon martial d\'époque Sengoku à 5 niveaux bardé de meurtrières, auquel a été adjointe en temps de paix (1634) une délicate aile d\'observation de la lune (Tsukimi-yagura) ceinte d\'un balcon laqué vermillon.','• Plus ancien donjon à 5 niveaux et 6 étages conservé au Japon (Trésor National).\\n• Contraste architectural saisissant entre le donjon de guerre et le pavillon de contemplation lunaire.\\n• Douves d\'eau vive profondes et système d\'archères et arquebusières (ya-sama et teppō-sama).','Le Cœur Stratégique de Shinano. Perché au carrefour des cols alpins, Matsumoto verrouille tout le centre de Honshū. Ses tireurs d\'élite et arquebusiers infligent des dégâts dévastateurs aux avant-gardes ennemies.','Regard du Corbeau de Shinano : Augmente de +20% la puissance d\'attaque des archers et unités à distance.',31,12,31,12,1,NULL,25000,NULL,NULL,'2026-09-15 09:49:35'),
(11,'matsuyama','Château de Matsuyama','Matsuyama-jō','松山城','Province d\'Iyo (Matsuyama, Préfecture d\'Ehime)','Katō Yoshiaki (1602 - 1628 / Rebâti 1854)','1628 / 1854','Bien Culturel Important & Citadelle Complexe de Colline','🏯','matsuyama.jpg','Formidable citadelle perchée sur le mont Katsuyama avec 21 dépendances historiques d\'origine reliées par des murailles crénelées.','Fondé par le valeureux général Katō Yoshiaki, l\'un des légendaires « Sept Lances de Shizugatake », le château de Matsuyama culmine sur la colline escarpée de Katsuyama (132 mètres) au cœur de la plaine de Dōgo. C\'est l\'un des rares exemples de donjon de style complexe relié (renritsu-shiki) encore existants : le donjon principal à trois niveaux est solidement ceinturé par des tourelles de défense et des coursives fortifiées formant une cour close imprenable. Il compte 21 bâtiments historiques préservés, représentant l\'un des ensembles fortifiés les plus complets du Japon féodal tardif.',
'• Ensemble fortifié de type renritsu-shiki avec 21 structures féodales authentiques.\\n• Portes doubles en chicane Tonan-mon et cours intérieures conçues pour l\'encerclement.\\n• Vue stratégique imprenable à 360° sur toute la mer intérieure de Seto.','Le Labyrinthe Invincible d\'Iyo. Sa succession de cours closes permet d\'absorber les assauts répétés et d\'organiser de foudroyantes contre-attaques de flanc.',
'Labyrinthe d\'Iyo : Réduit de -20% les pertes subies lors des sièges et assauts massifs.',-31,-12,-31,-12,1,NULL,25000,NULL,NULL,'2026-09-15 09:49:35'),
(12,'uwajima','Château d\'Uwajima','Uwajima-jō','宇和島城','Province d\'Iyo (Uwajima, Préfecture d\'Ehime)','Tōdō Takatora (1596 - 1601) / Date Munetoshi (1666)','1666','Bien Culturel Important & Joyau Géométrique de Takatora','🏯','uwajima.jpg','Chef-d\'œuvre du génie militaire Tōdō Takatora, donjon au plan pentagonal secret trompant la vue des assaillants.','Conçu par le plus brillant maître bâtisseur de forteresses du Japon féodal, Tōdō Takatora, le château d\'Uwajima a été perfectionné ultérieurement par Date Hidemune (fils aîné du célèbre Date Masamune, le « Dragon Borgne » de Sendai). Takatora y a appliqué son génie géométrique : le plan de l\'enceinte extérieure forme un pentagone irrégulier qui créait une illusion d\'optique chez les généraux ennemis, les incitant à attaquer sur un front pensé comme rectangulaire et les exposant immédiatement à des tirs de flanc mortels. Son donjon à trois étages conserve ses menuiseries raffinées de l\'ère Kanbun.','• Plan pentagonal ingénieux conçu par le maître architecte Tōdō Takatora.\\n• Donjon d\'époque Edo compact mais richement orné de pignons de style shoin.\\n• Forteresse côtière dominant le goulet stratégique de la baie d\'Uwajima.','La Clé Navale de Bungo. Contrôler Uwajima permet de maîtriser les liaisons maritimes entre Kyūshū et Shikoku, constituant la tête de pont idéale pour la bataille finale.',
'Géométrie Secrète de Takatora : Confère +10% de résistance globale et +15% de vitesse de navigation aux navires du clan.',-12,-31,-12,-31,1,NULL,25000,NULL,NULL,'2026-09-15 09:49:35');
/*!40000 ALTER TABLE `authentic_castles` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

